"""add document processing reliability fields

Revision ID: 6fdd145e1b8c
Revises: cee4d772f766
Create Date: 2026-08-31 12:28:56.134406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fdd145e1b8c'
down_revision: Union[str, Sequence[str], None] = 'cee4d772f766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'documents',
        sa.Column(
            'processing_attempts',
            sa.Integer(),
            nullable=False,
            server_default='0',
        ),
    )
    op.alter_column(
        'documents',
        'processing_attempts',
        server_default=None,
    )
    op.add_column('documents', sa.Column('last_processing_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('last_processing_finished_at', sa.DateTime(timezone=True), nullable=True))
    op.create_check_constraint(op.f('ck_documents_processing_attempts_non_negative'), 'documents', 'processing_attempts >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_documents_processing_attempts_non_negative'), 'documents', type_='check')
    op.drop_column('documents', 'last_processing_finished_at')
    op.drop_column('documents', 'last_processing_started_at')
    op.drop_column('documents', 'processing_attempts')
    # ### end Alembic commands ###
